
services:

  beetroot:
    container_name: beetroot-service
    build:
      context: ../
      dockerfile: Dockerfile
    image: ${REGISTRY_IMAGE}:${TAG}
    environment:
      - BEETROOT_JSON_PATH=/data/beetroot.json
    volumes:
      - ./data/beetroot.json:/data/beetroot.json:ro
    ports:
      - "8080:8080"
