services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.file.filename=/etc/traefik/config.yml
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8081:8080" # Optional: for Traefik dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config.yml:/etc/traefik/config.yml

  beetroot:
    image: ${REGISTRY_IMAGE}:${TAG}
    environment:
      - BEETROOT_JSON_PATH=/data/beetroot.json
    volumes:
      - ../data/beetroot.json:/data/beetroot.json:ro
    labels:
      - "traefik.http.routers.beetroot.rule=PathPrefix(`/`)"
      - "traefik.http.services.beetroot.loadbalancer.server.port=8080"
