services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  beetroot:
    image: ${REGISTRY_IMAGE}:${TAG}
    environment:
      - BEETROOT_JSON_PATH=/data/beetroot.json
    volumes:
      - ../data/beetroot.json:/data/beetroot.json:ro
